// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALFHvLlsz1q_QdH05qJDN-m3HDgTE9f0Q',
    appId: '1:54051735949:web:487c609cd51aab56df55c4',
    messagingSenderId: '54051735949',
    projectId: 'flutterapplication1-d9aa5',
    authDomain: 'flutterapplication1-d9aa5.firebaseapp.com',
    storageBucket: 'flutterapplication1-d9aa5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZa6N7J1HtxK3xNbkOZOLJx5K1wKYiKmc',
    appId: '1:54051735949:android:35337f179a42814ddf55c4',
    messagingSenderId: '54051735949',
    projectId: 'flutterapplication1-d9aa5',
    storageBucket: 'flutterapplication1-d9aa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzyc0USDNhMzmDCyCoTefj-oFdkUAuhiY',
    appId: '1:54051735949:ios:73dc3527aa7f918cdf55c4',
    messagingSenderId: '54051735949',
    projectId: 'flutterapplication1-d9aa5',
    storageBucket: 'flutterapplication1-d9aa5.appspot.com',
    iosClientId: '54051735949-65o1bkvma0bcvsng7b72dfuou7k1tbq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzyc0USDNhMzmDCyCoTefj-oFdkUAuhiY',
    appId: '1:54051735949:ios:73dc3527aa7f918cdf55c4',
    messagingSenderId: '54051735949',
    projectId: 'flutterapplication1-d9aa5',
    storageBucket: 'flutterapplication1-d9aa5.appspot.com',
    iosClientId: '54051735949-65o1bkvma0bcvsng7b72dfuou7k1tbq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
